### ISSUE TITLE
FeatureAdmin will not run on Server 2012 R2

### ISSUE THREAD

**Issue by Earthaddict** [achimismaili/featureadmin#3]
When I run Feature Admin on my windows 10 no problems, when i run it on our Dev SP2013 Server with Windows 2012 R2 it just closes with no real response. I checked the Smart screen is turned off.
![snag-0003 06-11-2018](https://user-images.githubusercontent.com/44807776/48067907-208c8400-e1da-11e8-9b75-879a8f28400b.png)

**Comment by achimismaili** [comment]
Oh, that's strange. Sorry to hear that.
I will look into that.

**Comment by randellhodges** [comment]
> Here is the Debug Info :Autofac.Core.DependencyResolutionException was unhandled
> Message: An unhandled exception of type 'Autofac.Core.DependencyResolutionException' occurred in WindowsBase.dll
> Additional information: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = AppViewModel (ReflectionActivator), Services = [FeatureAdmin.ViewModels.AppViewModel], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope
> 
> And Event Log:
> Application: FeatureAdmin.exe
> Framework Version: v4.0.30319
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.TypeLoadException
> at Akka.Serialization.NewtonSoftJsonSerializer..ctor(Akka.Actor.ExtendedActorSystem, Akka.Serialization.NewtonSoftJsonSerializerSettings)
> 
> Exception Info: System.Reflection.TargetInvocationException
> at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
> at System.Reflection.RuntimeConstructorInfo.Invoke(System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
> at System.RuntimeType.CreateInstanceImpl(System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo, System.Object[], System.Threading.StackCrawlMark ByRef)
> at System.Activator.CreateInstance(System.Type, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo, System.Object[])
> at System.Activator.CreateInstance(System.Type, System.Object[])
> at Akka.Serialization.Serialization..ctor(Akka.Actor.ExtendedActorSystem)
> at Akka.Actor.Internal.ActorSystemImpl..ctor(System.String, Akka.Configuration.Config)
> at FeatureAdmin.ActorSystemReference.CreateActorSystem()
> at FeatureAdmin.ActorSystemReference..cctor()
> 
> Exception Info: System.TypeInitializationException
> at FeatureAdmin.ActorSystemReference.get_ActorSystem()
> at FeatureAdmin.ViewModels.AppViewModel.InitializeActors()
> at FeatureAdmin.ViewModels.AppViewModel..ctor(Caliburn.Micro.IWindowManager, Caliburn.Micro.IEventAggregator, FeatureAdmin.Core.Repository.IFeatureRepository, FeatureAdmin.Core.Services.IDataService)
> at DynamicClass.lambda_method(System.Runtime.CompilerServices.Closure, System.Object[])
> at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
> 
> Exception Info: Autofac.Core.DependencyResolutionException
> at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
> at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(Autofac.IComponentContext, System.Collections.Generic.IEnumerable`1<Autofac.Core.Parameter>) at Autofac.Core.Resolving.InstanceLookup.Activate(System.Collections.Generic.IEnumerable`1<Autofac.Core.Parameter>)
> 
> Exception Info: Autofac.Core.DependencyResolutionException
> at Autofac.Core.Resolving.InstanceLookup.Activate(System.Collections.Generic.IEnumerable`1<Autofac.Core.Parameter>) at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(System.Guid, System.Func`1<System.Object>)
> at Autofac.Core.Resolving.InstanceLookup.Execute()
> at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(Autofac.Core.ISharingLifetimeScope, Autofac.Core.IComponentRegistration, System.Collections.Generic.IEnumerable`1<Autofac.Core.Parameter>) at Autofac.Core.Resolving.ResolveOperation.Execute(Autofac.Core.IComponentRegistration, System.Collections.Generic.IEnumerable`1<Autofac.Core.Parameter>)
> at Autofac.ResolutionExtensions.TryResolveService(Autofac.IComponentContext, Autofac.Core.Service, System.Collections.Generic.IEnumerable`1<Autofac.Core.Parameter>, System.Object ByRef) at Caliburn.Metro.Autofac.AutofacBootstrapper`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetInstance(System.Type, System.String)
> at Caliburn.Micro.BootstrapperBase.DisplayRootViewFor(System.Type, System.Collections.Generic.IDictionary`2<System.String,System.Object>)
> at System.Windows.Application.OnStartup(System.Windows.StartupEventArgs)
> at System.Windows.Application.<.ctor>b__1_0(System.Object)
> at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
> at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
> at System.Windows.Threading.DispatcherOperation.InvokeImpl()
> at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
> at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
> at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
> at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
> at System.Windows.Threading.DispatcherOperation.Invoke()
> at System.Windows.Threading.Dispatcher.ProcessQueue()
> at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
> at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
> at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
> at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
> at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
> at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
> at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
> at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
> at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
> at System.Windows.Application.RunDispatcher(System.Object)
> at System.Windows.Application.RunInternal(System.Windows.Window)
> at FeatureAdmin.App.Main()

What was your resolution to this? I have the same problem but on Server 2016 and SharePoint 2013.

**Comment by achimismaili** [comment]
Hey Randelhodges, 
I still don't know, how to reproduce this issue, please see my post from Nov 10th 18.
Could you describe a bit more what I am asking in there?
E.g., if your server runs in azure, do you have an ARM template and/or a description, how you set it up?
